micronaut:
  application:
    name: pixKeyManager
datasources:
  default:
    url: jdbc:mysql://localhost:3306/pix_api?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: andersonsantana
    password: banco
    dialect: org.hibernate.dialect.MySQL8Dialect
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

grpc:
  server:
    port: 50052

